### ISSUE TITLE
Tiles are hidden on a certain zoom level

### ISSUE THREAD

**Issue by Wilzi** [Leaflet/Leaflet.VectorGrid#102]
Hi,
First of all thank you for this great plugin!
I have a problem and found nothing related to this.
I load geoJSON to vector tiles, everything works great but it only shows the tiles when i zoom out.
If I zoom in to level >= 15 the tiles are hidden.
I've already tried the maxNativeZoom setting with no luck.

The examples from readme works the same

What should I set?
Thanks
Adam

**Comment by perliedman** [comment]
Hi!

It's a bit hard to tell without seeing your configuration, but it sounds like you have `maxZoom` set to 14 for your layer, which would hide it for zoom levels above 14.

**Comment by dnseminara** [comment]
@Wilzi, the default maxZoom seems to be set to 14 [here](https://github.com/Leaflet/Leaflet.VectorGrid/blob/master/src/Leaflet.VectorGrid.Slicer.js#L56)

It appears that you can add/use any of the [geojson-vt options](https://github.com/mapbox/geojson-vt#options) to `L.vectorGrid.slicer`

**Comment by perliedman** [comment]
Thanks, @dnseminara.

Closing this since there's no indication this is a bug in VectorGrid at this point.
