### ISSUE TITLE
Grid lines visible in geometry

### ISSUE THREAD

**Issue by wlievens** [Leaflet/Leaflet.VectorGrid#108]
Grid lines are visible in geometry when using the vector grid sourced from vector tiles. See the attached screenshot and look for the gray vertical and horizontal lines cutting through my geometry.

Is this an issue with the way I am generating my PVT geometry, or does Leaflet VectorGrid render it this way?

![gridlines](https://user-images.githubusercontent.com/1073326/27657149-f061c872-5c4b-11e7-8113-717c36a49cb7.png)

**Comment by perliedman** [comment]
I suspect your vector tiles are do not contain any overlap, which can cause this. This is not an inherent behaviour in VectorGrid, as you can see from the examples.

**Comment by wlievens** [comment]
So you suspect there is something wrong with how I generate the vectors in the backend? Is there supposed to be a small margin for overlap, or what do you mean with the term "overlap"?

**Comment by perliedman** [comment]
Yes, it is common practice to clip geometries a bit outside the tile's limits, in practice causing a bit of overlap, to avoid rounding problems causing the effect you show.

See https://www.mapbox.com/vector-tiles/specification/#clipping for some discussion of this.

**Comment by wlievens** [comment]
I assume I should not just hack that in by extending the tile geomrtry (the envelope) as that would screw up how the tiles are aligned. It should probably be some option in the library I use for the backend, so I will explore there. Thanks for the pointers!

**Comment by particracy** [comment]
Just updating in case anyone is interested: I've raised this issue (https://github.com/wdtinc/mapbox-vector-tile-java/issues/5) with the backend library (**mapbox-vector-tile-java**) and its helpful maintainer has resolved the issue and has released a new version.

**Comment by wlievens** [comment]
Just updating in case anyone is interested: I've raised this issue (https://github.com/wdtinc/mapbox-vector-tile-java/issues/5) with the backend library (**mapbox-vector-tile-java**) and its helpful maintainer has resolved the issue and has released a new version.
