### ISSUE TITLE
Rendering Problem of points

### ISSUE THREAD

**Issue by bloigge** [Leaflet/Leaflet.VectorGrid#110]
Hi,

We are using pbfs from a geoserver group-layer, which contains points, lines and polygons. Lines and polygons work as expected but for some reason points don't get rendered properly in border areas when using circle markers or icons.

![chrome_2017-07-31_12-11-28](https://user-images.githubusercontent.com/7089726/28773357-871ed474-75e9-11e7-84b5-615d6516605c.png)

![chrome_2017-07-31_12-24-03](https://user-images.githubusercontent.com/7089726/28773780-383f5c96-75eb-11e7-9b92-2c9d325e0b5f.png)

I am not sure if this is an issue with geoserver concerning the overlapping margins for each tile or a Leaflet.VectorGrid bug.

**Comment by bloigge** [comment]
Same issue has been noted here [#63](https://github.com/Leaflet/Leaflet.VectorGrid/issues/63) as well

**Comment by perliedman** [comment]
I suspect this is an issue similar to #108, that is you don't have enough overlap between your tiles, which causes points to only be rendered on one side of the tile boundary.

For rendering to be correct when the symbol would overlap a tile boundary, the point must be present in both of the tiles, and therefore also rendered twice. This becomes especially apparent when working with large symbols.

**Comment by bloigge** [comment]
Ok thanks for clarification. I already increased the metatile size and the extra pixel border in the geoserver grouplayer settings but unfortunately it doesn't work. As a workaround I changed the the icon size to be very small. I am not sure how mapbox-gl  works under the hood, but using the same source didn't create this behavior there:
![chrome_2017-08-01_11-45-09](https://user-images.githubusercontent.com/7089726/28819590-ff366ca4-76ae-11e7-9c27-361ec257fb53.png)

**Comment by perliedman** [comment]
Hm, that is weird. Regarding how Mapbox GL works, you can get the general idea by reading the vector tile spec's section on clipping, if you haven't already: https://www.mapbox.com/vector-tiles/specification/#clipping

**Comment by TroySchmidt** [comment]
For someone else finding this and looking for better direction, add ```buffer``` parameter to your options object you pass to ```L.vectorGrid.slicer```.  I set mine to 500 and now it is working as I would expect.

**Comment by mngyng** [comment]
See #149. Sounds like the same issue. The buffer option didn't work for me, so I changed the query to add a buffer for points on the tile edge.
