### ISSUE TITLE
Custom JSON vector grid

### ISSUE THREAD

**Issue by c-martinez** [Leaflet/Leaflet.VectorGrid#116]
I am trying to load a custom JSON for each vector tile. So whenever I zoom in/out / move around, I want to load a different chunk of JSON data. I am doing some data plotting using the JSON data from the different layers.

When zooming in and out, I am hooking up to the `zoomend` event to refresh the plots. However this does not work when the map is loaded for the first time. Is there any other event which I could hook up to? Or (even better) are is there a function / event which `VectorGrid` calls / notifies when it starts and finishes loading data?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by c-martinez** [comment]
Fiddle: https://jsfiddle.net/cmartinez/qw0bdd9a/1/

Basically I would like to:
 - Have a data store (an array or so) where data for each tile is appended
 - When each tile loads its data, to be able to append it to the data store
 - When zoom level changes, to be able to flush the data store.

**Comment by perliedman** [comment]
If I understand correctly, you want to create support for another data format than VectorGrid already supports (GeoJSON, MVT). However, I'm not sure I understand how this relates to hooking up to `zoomend` or other events - VectorGrid will automatically update its tiles whenever the map is zoomed, so this is not something you would have to implement. The same goes for moving around (panning): already handled by VectorGrid (or rather by `L.GridLayer`, which VectorGrid uses).

So, for me, it's a bit unclear what the actual question here is?

**Comment by c-martinez** [comment]
Indeed what I am aiming is for another data format. The reason why I want (or at least I think I want) to hook up to an event is because I want to know when the data from my custom format has finished loading so I can start processing. For example, I could trigger drawing of a pie chart with the data from my custom format.

Does this make sense? Or am I approaching the problem the wrong way?

**Comment by perliedman** [comment]
Oh, if all you need is to know when the tile is loaded, you should listen for the [`tileload`](http://leafletjs.com/reference-1.2.0.html#gridlayer-tileload) event, or possibly just the layer's [`load`](http://leafletjs.com/reference-1.2.0.html#gridlayer-load) event, they will fire once the data is actually loaded.

**Comment by c-martinez** [comment]
Aha! I think that is just what I needed. Thanks!
