### ISSUE TITLE
interactive not work in protobuf.

### ISSUE THREAD

**Issue by cdqrain** [Leaflet/Leaflet.VectorGrid#117]
Hi all.
I use L.vectorGrid.protobuf to load mapbox vector tile, then set the "interactive: true" and add "mouseover" or "click" event on the layer. but the event was not triggled.
I modified the "createTile" function to fit my custom projection, does it effect the interactive ?

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour?

**Comment by cdqrain** [comment]
Hi IvanSanchez.
I publish a plnkr. But for the CORS reason, it can not load my "mvt" files.  What should I do ? 
http://plnkr.co/edit/NQaMXUOx1mRiwTLWY6DW?p=preview

**Comment by cdqrain** [comment]
Hi IvanSanchez.
I have updated my mvt service, now it can load the mvt files.

**Comment by perliedman** [comment]
> I modified the "createTile" function to fit my custom projection, does it effect the interactive ?

@cdqrain does that mean that your example is running a _modified_ version of Leaflet.VectorGrid? That's unfortunately not possible for us to support, especially not when we don't know what those changes are. Please understand that we have limited time to examine issue reports.

If VectorGrid isn't compatible with custom projections, we should start by opening an issue for that and fix it.

**Comment by cdqrain** [comment]
@perliedman  I just only modify "createTile" function. Does it affect the interactive ? 
I don't know where to start to fix VectorGrid custom projection.

**Comment by cdqrain** [comment]
@IvanSanchez @perliedman  I removed "rendererFactory: L.canvas.tile", the interactive can work.
