### ISSUE TITLE
Offline .pbf files not working: ERROR Error: Unimplemented type: 3

### ISSUE THREAD

**Issue by rklerck** [Leaflet/Leaflet.VectorGrid#121]
Hi,

Not an issue, more a question.. Is there a way to make offline pbf files work? I exported a mbtiles file to multiple pbf files and changed the url served to:

`L.vectorGrid.protobuf("assets/tiles/14/8680/8100.pbf`

But than I receive the error: ERROR Error: Unimplemented type: 3. This probably has something to do with gzip encoding(?) but I can't get it to work...

**Comment by IvanSanchez** [comment]
Please provide a protobuf tile (or a few), your version of VectorGrid (as well as the `vectortile` dependency, if not using the default or building your own), and a full stack trace. There is not enough information to know what's going on.

**Comment by rklerck** [comment]
[Tiles.zip](https://github.com/Leaflet/Leaflet.VectorGrid/files/1311870/Tiles.zip)

Sorry! I've added a few tiles. I used Mbutil to extract the pbf's from the mbtiles file.

These are the versions in my package.json:

```
"leaflet": "^1.0.3",
"leaflet.vectorgrid": "^1.3.0",
```

Not sure where to find the vectortile dependency...

And the stacktrace:

```
ERROR Error: Unimplemented type: 3
    at g (polyfills.js:3)
    at Pbf.skip (main.js:115619)
    at Pbf.readFields (main.js:115619)
    at new VectorTileLayer$2 (main.js:115619)
    at readTile (main.js:115619)
    at Pbf.readFields (main.js:115619)
    at new VectorTile$1 (main.js:115619)
    at FileReader.<anonymous> (main.js:115619)
    at t.invokeTask (polyfills.js:3)
    at Object.onInvokeTask (main.js:4415)
    at t.invokeTask (polyfills.js:3)
    at n.runTask (polyfills.js:3)
    at FileReader.invoke (polyfills.js:3)
```

Is this enough?

**Comment by IvanSanchez** [comment]
ugh, `main.js:115619` looks like you don't have sourcemaps for those. Any chance to tell which library is involved in each step of the stack trace?

**Comment by rklerck** [comment]
Well, don't know if this is what you're looking for? This is the source from where it goes wrong.

```
var reader = new FileReader();
				return new Promise(function(resolve){
					reader.addEventListener("loadend", function() {
						// reader.result contains the contents of blob as a typed array

						// blob.type === 'application/x-protobuf'
						var pbf = new Pbf( reader.result );
// 						console.log(pbf);
						return resolve(new VectorTile( pbf ));

					});
					reader.readAsArrayBuffer(blob);
				});
```

**Comment by IvanSanchez** [comment]
I'm gonna guess that VectorGrid is behaving as expected, and passing the protobuffer to [Mapbox's `vector-tile`](https://www.npmjs.com/package/@mapbox/vector-tile) for decoding, and something in there is crashing. I would even go as far as guessing that the problem might be either malformed vector tiles or a conflicting old version of `vector-tile`.

I suggest you try to debug this in a small stand-alone nodejs script, reading a .pbf file, creating an instance of `Pbf` (via [`pbf`](https://www.npmjs.com/package/pbf))and then instantiating a `VectorTile`. That should trigger the same error.

So far this is not looking as a VectorGrid bug. I'm tempted to close it unless it can be reproduced with a readily available vector tile source.

**Comment by rklerck** [comment]
I will close it, I found the issue. I had to use gzip to decompress the .pbf file! Thanks for the help @IvanSanchez

**Comment by leye0** [comment]
As I have the same issue as above, I'd like to comment here. I'm producing pbf vector tiles using tilemaker. My tiles look like so. The error message is exactly as above: Unimplemented Type 3.

My tiles appear to be gzip as gunziping them will produce a much larger file. I tried to serve them zipped and unzipped with no chance.

Here are two samples.

[leye0-Tiles.zip](https://github.com/Leaflet/Leaflet.VectorGrid/files/1807243/leye0-Tiles.zip)

Are tiles produced with https://github.com/systemed/tilemaker compliant with this plugin?

**Comment by leye0** [comment]
@rklerck Could I be in a case similar to yours?

**Comment by tomchadwin** [comment]
> Are tiles produced with https://github.com/systemed/tilemaker compliant with this plugin?

@systemed?

**Comment by miguelcobain** [comment]
I'm also using https://github.com/systemed/tilemaker to produce the tiles and ended up with the same `Uncaught Error: Unimplemented type: 3`.

**Comment by systemed** [comment]
It's almost certainly a compression issue as per above.

**Comment by miguelcobain** [comment]
@systemed any suggestion you could think of for fixing this?
Does `tilemaker` compress the output tile files?

**Comment by miguelcobain** [comment]
Indeed, it was a compression issue.
When I configured tilemaker to not compress output files and then served them normally (without any gzip headers, etc), it all worked out. 
Thank you!

**Comment by systemed** [comment]
Excellent!
