### ISSUE TITLE
Uncaught TypeError: Cannot read property 'slicer' of undefined

### ISSUE THREAD

**Issue by soli004** [Leaflet/Leaflet.VectorGrid#150]
I have this issue when using Leaflet.draw together with Leaflet.VectorGrid.

Everything works fine except when I put in this into index.html as a test for using VectorGrid I get this error "Uncaught TypeError: Cannot read property 'slicer' of undefined". How to solve this?

`    var geojson = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"Name":"test","Number":2.25,"Size":45},"geometry":{"type":"Point","coordinates":[59.5,14.5]}}]}
    
    var canvasTile =L.vectorGrid.slicer(geojson,{
                    interactive: true,
                    rendererFactory: L.canvas.tile,
                    vectorTileLayerStyles:{
                        sliced:{ icon: new L.Icon.Default()}
                    }
                    }).addTo(map);
        canvasTile.on('click', function(e) {
                        var pro = e.layer.properties;
                        var HTML = '';
                        for (var q in pro) {
                            HTML += q + ":" + pro[q] + '<br />';
                        }
                        L.popup()
                            .setContent(HTML)
                            .setLatLng(e.latlng)
                            .openOn(map);
                        
                    })`

**Comment by soli004** [comment]
This is the index file

` <!DOCTYPE html>
<html lang="sv">
<head>

  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">


    <title>Test Leaflet</title>

    <link rel="stylesheet" type="text/css" href="css/leaflet.awesome-markers.css">

    <script defer src="https://use.fontawesome.com/releases/v5.0.8/js/all.js"></script>
    <script type="text/javascript" src="libs/jquery-3.2.1.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet/1.3.1/leaflet.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/leaflet-ajax/2.1.0/leaflet.ajax.min.js"></script>
    <script src="https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js"></script>
    <script src="https://unpkg.com/leaflet.vectorgrid@1.3.0/dist/Leaflet.VectorGrid.js"></script>
    <script src="https://use.fontawesome.com/f9c4556da9.js"></script>



    <script src="libs/leaflet-src.js"></script>
    <link rel="stylesheet" href="libs/leaflet.css" />

    <script src="src/Leaflet.draw.js"></script>
    <script src="src/Leaflet.Draw.Event.js"></script>
    <link rel="stylesheet" href="src/leaflet.draw.css" />

    <script src="src/Toolbar.js"></script>
    <script src="src/Tooltip.js"></script>

    <script src="src/ext/GeometryUtil.js"></script>
    <script src="src/ext/LatLngUtil.js"></script>
    <script src="src/ext/LineUtil.Intersect.js"></script>
    <script src="src/ext/Polygon.Intersect.js"></script>
    <script src="src/ext/Polyline.Intersect.js"></script>
    <script src="src/ext/TouchEvents.js"></script>

    <script src="src/draw/DrawToolbar.js"></script>
    <script src="src/draw/handler/Draw.Feature.js"></script>
    <script src="src/draw/handler/Draw.SimpleShape.js"></script>
    <script src="src/draw/handler/Draw.Polyline.js"></script>
    <script src="src/draw/handler/Draw.Marker.js"></script>
    <script src="src/draw/handler/Draw.CircleMarker.js"></script>
    <script src="src/draw/handler/Draw.Circle.js"></script>
    <script src="src/draw/handler/Draw.Polygon.js"></script>
    <script src="src/draw/handler/Draw.Rectangle.js"></script>


    <script src="src/edit/EditToolbar.js"></script>
    <script src="src/edit/handler/EditToolbar.Edit.js"></script>
    <script src="src/edit/handler/EditToolbar.Delete.js"></script>

    <script src="src/Control.Draw.js"></script>

    <script src="src/edit/handler/Edit.Poly.js"></script>
    <script src="src/edit/handler/Edit.SimpleShape.js"></script>
    <script src="src/edit/handler/Edit.Marker.js"></script>
    <script src="src/edit/handler/Edit.CircleMarker.js"></script>
    <script src="src/edit/handler/Edit.Circle.js"></script>
    <script src="src/edit/handler/Edit.Rectangle.js"></script>


      
    <script type="text/javascript" src="src/tatort_2000.js"></script>
    <script type="text/javascript" src="src/tatort_5000.js"></script>
    <script type="text/javascript" src="src/tatort_10000.js"></script>
    <script type="text/javascript" src="src/tatort_20000.js"></script>
    <script type="text/javascript" src="src/tatort_30000.js"></script>
    <script type="text/javascript" src="src/tatort_50000.js"></script>
    <script type="text/javascript" src="src/tatort_100000.js"></script>
    <script type="text/javascript" src="src/tatort_large.js"></script>
    <script type="text/javascript" src="src/opoints.js"></script>
    <script type="text/javascript" src="src/upoints.js"></script>
    <script type="text/javascript" src="src/fpoints.js"></script>
    <script type="text/javascript" src="src/brl.js"></script>
    <script type="text/javascript" src="src/brl_14.js"></script>
    <script type="text/javascript" src="src/brl_17.js"></script>
    <script type="text/javascript" src="src/brl_18.js"></script>




</head>
<body>
    <div id="map" style="width: 1000px; height: 800px; border: 1px solid #ccc"></div>

    <script>

        var osmUrl = 'http://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',
            osmAttrib = '&copy; <a href="http://openstreetmap.org/copyright">OpenStreetMap</a> contributors',
            osm = L.tileLayer(osmUrl, {maxZoom: 18, attribution: osmAttrib}),
            map = new L.Map('map', {center: new L.LatLng(59.5, 14.5), zoom: 7}),
            drawnItems = L.featureGroup().addTo(map);

        L.control.layers({
            "OpenStreetMap": osm.addTo(map),
            "OpenStreetMap_BW": L.tileLayer('https://cartodb-basemaps-{s}.global.ssl.fastly.net/light_all/{z}/{x}/{y}.png', {
                attribution: '&copy; <a href="http://www.openstreetmap.org/copyright">OpenStreetMap</a> &copy; <a href="http://cartodb.com/attributions">CartoDB</a>'
            })
        }, 
        {

        'Draw Layer': drawnItems,
        'Tätort <= 2000': tatort_2000,
        'Tätort 2000 till 5000': tatort_two2five,
        'Tätort 5000 till 10000': tatort_five2ten,
        'Tätort 10000 till 20000': tatort_ten2twenty,
        'Tätort 20000 till 30000': tatort_twenty2thirty,
        'Tätort 30000 till 50000': tatort_thirty2fifty,
        'Tätort 50000 till 100000': tatort_fifty2hundred,
        'Tätort >=100000': tatort_large


        }, 
        { position: 'topright', collapsed: true }).addTo(map);

        map.addControl(new L.Control.Draw({
            edit: {
                featureGroup: drawnItems,
                poly : {
                    allowIntersection : false
                }
            },
            draw: {
                polygon : {
                    allowIntersection: false,
                    showArea:true
                }
            }
        }));

        // Truncate value based on number of decimals
        var _round = function(num, len) {
            return Math.round(num*(Math.pow(10, len)))/(Math.pow(10, len));
        };
        // Helper method to format LatLng object (x.xxxxxx, y.yyyyyy)
        var strLatLng = function(latlng) {
            return "("+_round(latlng.lat, 6)+", "+_round(latlng.lng, 6)+")";
        };

        // Generate popup content based on layer type
        // - Returns HTML string, or null if unknown object
        var getPopupContent = function(layer) {
            // Marker - add lat/long
            if (layer instanceof L.Marker || layer instanceof L.CircleMarker) {
                return strLatLng(layer.getLatLng());
            // Circle - lat/long, radius
            } else if (layer instanceof L.Circle) {
                var center = layer.getLatLng(),
                    radius = layer.getRadius();
                return "Center: "+strLatLng(center)+"<br />"
                      +"Radius: "+_round(radius, 2)+" m";
            // Rectangle/Polygon - area
            } else if (layer instanceof L.Polygon) {
                var latlngs = layer._defaultShape ? layer._defaultShape() : layer.getLatLngs(),
                    area = L.GeometryUtil.geodesicArea(latlngs);
                return "Area: "+L.GeometryUtil.readableArea(area, true);
            // Polyline - distance
            } else if (layer instanceof L.Polyline) {
                var latlngs = layer._defaultShape ? layer._defaultShape() : layer.getLatLngs(),
                    distance = 0;
                if (latlngs.length < 2) {
                    return "Distance: N/A";
                } else {
                    for (var i = 0; i < latlngs.length-1; i++) {
                        distance += latlngs[i].distanceTo(latlngs[i+1]);
                    }
                    return "Distance: "+_round(distance, 2)+" m";
                }
            }
            return null;
        };

        // Object created - bind popup to layer, add to feature group
        map.on(L.Draw.Event.CREATED, function(event) {
            var layer = event.layer;
            var content = getPopupContent(layer);
            if (content !== null) {
                layer.bindPopup(content);
            }
            drawnItems.addLayer(layer);
        });

        // Object(s) edited - update popups
        map.on(L.Draw.Event.EDITED, function(event) {
            var layers = event.layers,
                content = null;
            layers.eachLayer(function(layer) {
                content = getPopupContent(layer);
                if (content !== null) {
                    layer.setPopupContent(content);
                }
            });
        });


    var geojson = {"type":"FeatureCollection","features":[{"type":"Feature","properties":{"Name":"test","Number":2.25,"Size":45},"geometry":{"type":"Point","coordinates":[59.5,14.5]}}]}
    
    var canvasTile =L.vectorGrid.slicer(geojson,{
                    interactive: true,
                    rendererFactory: L.canvas.tile,
                    vectorTileLayerStyles:{
                        sliced:{ icon: new L.Icon.Default()}
                    }
                    }).addTo(map);
        canvasTile.on('click', function(e) {
                        var pro = e.layer.properties;
                        var HTML = '';
                        for (var q in pro) {
                            HTML += q + ":" + pro[q] + '<br />';
                        }
                        L.popup()
                            .setContent(HTML)
                            .setLatLng(e.latlng)
                            .openOn(map);
                        
                    })


    </script>
</body>
</html>`

**Comment by soli004** [comment]
![printscreen 2018-03-10 kl 08 47 45](https://user-images.githubusercontent.com/5410735/37239636-ce7c4bc6-243f-11e8-9263-a923eb774cbd.jpg)
![printscreen 2018-03-10 kl 08 47 16](https://user-images.githubusercontent.com/5410735/37239637-d15e3b42-243f-11e8-9ce2-cb07d2166e7b.jpg)

**Comment by manuamador** [comment]
GeoJSON may be a protected name.
Have you tried to rename your var ?

**Comment by JamesMilnerUK** [comment]
I would firstly recommend adding a <head> and <body> block to your HTML and moving all of your script tags to the end of the <body> block, making sure Leaflet is loaded in first. It also looks like perhaps you load in another Leaflet by accident via ```<script src="libs/leaflet-src.js"></script>```.

**Comment by soli004** [comment]
I did cancel out the leaflet-src.js (thought it was needed for leaflet.draw) I did move around a bit and tried to clean it up as good as I could. I have no problem adding point but as soon as I want to use polygons with (geojson files) and VectorGrid I'm out of luck. I have some very large polygon files I want to put up so need to use VectorGrid. I have put up an example here [www.digitalworkflow.se/leaflet/](url) What is wrong and how should I correct it? Thanks....

**Comment by soli004** [comment]
Finally got it fixed... :)

**Comment by tomchadwin** [comment]
How? It will help others if you can give more details.

**Comment by soli004** [comment]
Actually the issue went away when I removed the second leaflet as JamesMilnerUK suggested and I also did not use GeoJson as manuamador comment on. I did also remove awesome fonts scripts as a start, tried to remove as much as I could and start build up from there. This is the changes for the vector grid part...

`var new_polygon = new L.layerGroup();

$.getJSON("../data/area.geojson", function(json) {

    var vectorGrid =  L.vectorGrid.slicer(json, {
                      mazZoom: 20,
                      rendererFactory: L.svg.tile,
                      vectorTileLayerStyles: {
                          sliced: {
                          weight: 4,
                          color: 'black',
                          opacity: 0.8,
                          fill: true,
                          stroke: true,
                          fillOpacity: 0

                          } 
                         },
                         interactive: true,
                       }) 

     .on('click', function(e) {
      var properties = e.layer.properties;
      L.popup()
        .setContent(
          "<b>Name</b>: " + properties.name + 
          "<br><b>Sum</b>: " + properties.sum + " st" +
          "<br><b>AreaID</b>: " + properties.areaID)
        .setLatLng(e.latlng)
        .openOn(map);
                        })
    vectorGrid.addTo(new_polygon)

                }) `
