### ISSUE TITLE
Enable cookies with the fetch API.

### ISSUE THREAD

**Issue by dbauszus-glx** [Leaflet/Leaflet.VectorGrid#169]
Is there a way to enable cookies in the fetch API which is bundled with VectorGrid?

I just ran into an endpoint which requires tile requests to have a cookie for authorization.

**Comment by IvanSanchez** [comment]
https://stackoverflow.com/questions/34558264/fetch-api-with-cookie

**Comment by dbauszus-glx** [comment]
Nice. Is it possible to pass the `credentials: include` option through VectorGrid to Leaflet or is this something I need to enable in Leaflet itself?

**Comment by dbauszus-glx** [comment]
I guess it is this one... https://github.com/Leaflet/Leaflet/pull/6016
