### ISSUE TITLE
Read Geojson of a protobuf layer

### ISSUE THREAD

**Issue by Zahma** [Leaflet/Leaflet.VectorGrid#176]
Hello,
I'm wondering if there is anyway to retrive the geojson coordinates of a protobuf polygon. as in L.Layers in leaflet, there is a method called .toGeoJSON(). 

thank you

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by chwahab** [comment]
```var gridLayer = L.vectorGrid.protobuf("http://localhost/tileserver/grid/{z}/{x}/{y}.pbf", {```
            ```vectorTileLayerStyles: {
                musafa_grid: (properties, zoom) =>{
                    return {
                        weight: 4,
                        color: '#cf52d3',
                        dashArray: '2, 6',
                        fillOpacity: 0.7
                    }
                }
            },
            getFeatureId: (f) => {
                return f.properties.id;
            },
            maxNativeZoom: 20,
            minZoom: 18,
            interactive: true,
            rendererFactory: L.canvas.tile,
            pane: 'overlayPane'
        }).on('click', (e) => {
            var coords= [];
            var zoom = this.map.getZoom();
            e.layer._parts[0].forEach((p) => {
                coords.push(map.layerPointToLatLng(p));
            });
            L.polygon([coords], {color: 'red'}).addTo(map);
        }).addTo(map);```
        But it did generate polygon at different location
