### ISSUE TITLE
Can I use the entire canvas to render instead of generating a canvas for each tile?

### ISSUE THREAD

**Issue by gee1k** [Leaflet/Leaflet.VectorGrid#182]
Can I use the entire canvas to render instead of generating a canvas for each tile?

**Comment by tomchadwin** [comment]
I don't think so, as that's fundamental to how VectorGrid works. Each canvas is rendered with a buffer which is subsequently clipped. But others know better than I.

**Comment by IvanSanchez** [comment]
No. Using one canvas per tile is exactly the point of vectorgrid.

It might be possible to make a crossover between VectorGrid and L.TileLayer.NoGap, but that requires work.

**Comment by IvanSanchez** [comment]
> Each canvas is rendered with a buffer which is subsequently clipped.

Not really - there is no buffer in the canvas itself. The *coordinates* of the vector data might form a buffer around each canvas, but the pixels that fall outside the canvas are not drawn AFAIK.

See the SVG viewbox for comparison, it works in a similar way (there might be stuff outside the viewbox, but that'll be just cropped): https://github.com/Leaflet/Leaflet.VectorGrid/blob/3a336694a82dc45c6c96746c2cd01193cf1ba0f2/src/Leaflet.Renderer.SVG.Tile.js#L13

**Comment by gee1k** [comment]
Each tile generates a canvas separately, and there will be problems like #110 . If you use the entire canvas, this problem will not occur. I think the mapbox seems to be like this.

**Comment by IvanSanchez** [comment]
...and that would mean clipping lines/polygons but not points (circles/images), extending/cropping the canvas on map pan, and a whole new set of problems. I understand what you mean, but I'm afraid your approach is naïve.
