### ISSUE TITLE
can't display protobuf layer

### ISSUE THREAD

**Issue by 2803media** [Leaflet/Leaflet.VectorGrid#189]
Hi I'm stuck and don't know what's not working

I have a geojson:

https://2803.ovh/lecadastre/tileserver/cadastre-59205-parcelles.json

I convert it with tippecanoe:

```tippecanoe -o new259205.mbtiles -zg --drop-densest-as-needed --no-tile-compression cadastre-59205-parcelles.json```

and upload to my server where tileserver-php is located

And create this leaflet vectorgrid map: 

```
	var map = L.map('map', {
  measureControl: true}).setView([50.333764833496, 3.3377838134766], 14);

		var grayscale = L.tileLayer.provider('CartoDB.Positron',{minZoom: 8, maxZoom: 20}),
    	streets   = L.tileLayer.provider('Esri.WorldImagery',{minZoom: 8, maxZoom: 20}),
			cadastreview = L.tileLayer('',{minZoom: 8, maxZoom: 20})
			;

		var baseMaps = {
			"Vue cadastre": cadastreview,
			"Vue cartographique": grayscale,
			"Vue satellite": streets,
		};

          defaultLayer = L.tileLayer.provider('CartoDB.Positron',{minZoom: 8, maxZoom: 20}).addTo(map);
        //defaultLayer.on("load",function() { console.log("all visible tiles have been loaded") });

    map.addLayer(defaultLayer);

		map.on("baselayerchange", function (event) {
				map.removeLayer(defaultLayer);
		  	if(typeof vectorGrid != 'undefined'){
					vectorGrid.bringToFront();
				}
				if(typeof vectorGrid2 != 'undefined'){
					vectorGrid2.bringToFront();
				}
				console.log(event.layer);
		});

		map.scrollWheelZoom.disable();

		//var geocoder = L.control.geocoder('search-MKZrG6M').addTo(map);

    var lat = 50.333764833496;
		var lng = 3.3377838134766;
		latlng = L.latLng(lat, lng);
		console.log(latlng);

      var mapboxUrl = "//2803.ovh/lecadastre/tileserver/tileserver.php?/index.json?/new259205/{z}/{x}/{y}.pbf";

      var mapboxVectorTileOptions = {
        rendererFactory: L.canvas.tile,
      };

      var mapboxPbfLayer = L.vectorGrid.protobuf(mapboxUrl, mapboxVectorTileOptions).addTo(map);

```

And get this error:

```
Uncaught Error: Unimplemented type: 3
    at Pbf.skip (Leaflet.VectorGrid.bundled.min.js:1)
    at Pbf.readFields (Leaflet.VectorGrid.bundled.min.js:1)
    at new VectorTile$1 (Leaflet.VectorGrid.bundled.min.js:1)
    at FileReader.<anonymous> (Leaflet.VectorGrid.bundled.min.js:1)
```

As you see i create the mbtile without compression and can't find why it's failed.

The live url on my test is just here: https://2803.ovh/lecadastre/tileserver/test.php

Any input to debug is welcome!

**Comment by zawarski** [comment]
Nothing to add, except I am having this same issue.

**Comment by zawarski** [comment]
I figured out I was getting that error because my tiles were compressed. I tried the link you provided:

https://2803.ovh/lecadastre/tileserver/cadastre-59205-parcelles.json

And when I view the network log in chrome, all the pbf entries say "{"message":"Tile does not exist"}".

**Comment by 2803media** [comment]
as you can see it works with mapbox : https://2803.ovh/lecadastre/tileserver/tileserver.php#bati/mapboxgl
But not with leaflet vectogrid : https://2803.ovh/lecadastre/tileserver/test.php

**Comment by zawarski** [comment]
I *was* successful in adding and displaying the https://2803.ovh/lecadastre layer. Using [50.331434,3.361816], 14 as the setview, it is not shown, however, if I zoom way,way out, I see a blue dot, zoom in and there is your layer. Sorry I don't have the lat/lon that I am seeing it at. I can figure it out if you need me to, but I was able to see it.
