### ISSUE TITLE
Discussion: fetch not available in IE

### ISSUE THREAD

**Issue by t-sch** [Leaflet/Leaflet.VectorGrid#19]
Under Internet Explorer _fetch_ is not supported, so _ _getVectorTilePromise()_ doesn't work.

I wrote a replacement for _ _getVectorTilePromise()_ that uses JQuery's _$.ajax()_. This solution works on all browsers I tested (IE, Edge, Chrome, FF, Safari). The problem with this approach is it needs JQuery and an initialization routine that enables binary buffer transfers.

Currently I have no dynamic selection of fetch vs. JQuery so it's not 'universal'.

- Should I write a pull request?
- Is a dynamic switch necessary?

Your ideas are appreciated.

-Thomas

**Comment by IvanSanchez** [comment]
Use a `fetch` polyfill.

**Comment by t-sch** [comment]
Thanks, I tried that and it works, albeit I have the impression the tiles load slower...
