### ISSUE TITLE
How can I use style.json with L.VectorGrid.Protobuf ?

### ISSUE THREAD

**Issue by SuperPat45** [Leaflet/Leaflet.VectorGrid#196]
I'm surprised it seem not possible to init a L.VectorGrid.Protobuf tile layer with a style.json file provided by TileServerGL/maptiller.com like in this demo:
https://www.maptiler.com/maps/#streets//vector/3/-74/40.73
style.json:
https://api.maptiler.com/maps/streets/style.json?key=R8rAisQ0L6EL1wW8JVYQ

Can I use style.json file description to load a map with L.VectorGrid.Protobuf ?

**Comment by IvanSanchez** [comment]
> Can I use `style.json` file description to load a map with L.VectorGrid.Protobuf ?

No.

There was some work done in the [`mapbox` branch](https://github.com/Leaflet/Leaflet.VectorGrid/tree/mapbox), but it was never finished. Finishing up that work would be awesome.
