### ISSUE TITLE
Mouse events over Points result in error

### ISSUE THREAD

**Issue by abuehlmann** [Leaflet/Leaflet.VectorGrid#210]
Hi and first of all, Thank's for all the great work.

I'm having troubles with mouseover, mouseout and click events over Points in a Leaflet.VectorGrid. This functionality was working fine (popup over point appeared after click), but since the update of leaflet to version 1.5.1 (I was using the version 1.3.4 of leaflet before), the following error occurs:
 _Uncaught TypeError: Cannot read property 'lat' of undefined_
This error comes from leaflet. Over Lines and areas, the mouseover works properly and a click on these shapes opens the popup

An example of the error is found at the following Link when hovering over one of the green points:
https://hydromaps.ch/#en/14/46.7926/7.8932/bl_hds--d01_hydrogeology$0

Do you have any suggestions how to handle this?

best,
Alain

**Comment by tomchadwin** [comment]
This is discussed in #148, where you should find details of how things currently stand with this issue.

**Comment by abuehlmann** [comment]
Thank you very much, and sorry for the double request. It worked perfect.
