### ISSUE TITLE
remove Polygon boundary in style

### ISSUE THREAD

**Issue by am2222** [Leaflet/Leaflet.VectorGrid#226]
Hi,
I am trying to remove the polygon boundary but it seems it is not working. Am I doing something wrong in my style?
here is my style object
```
return style = {
				fill: true,
				stroke: false,
				fillColor: options.colorFunction(properties.VALUE),
				color: options.colorFunction(properties.VALUE),
				weight: 0,
				fillOpacity: 1,
				opacity: 0
			}

```

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by am2222** [comment]
@IvanSanchez thanks. I thought it is something related to this library. So the style which is used here is leaflet's regular style. right?

**Comment by IvanSanchez** [comment]
Yes, but wrapped around, so VectorGrid can handle several layers in the same vector tile source. I guess you've read through https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html , right?

**Comment by am2222** [comment]
Yes, I ended up with this style
```
	fill: true,
	stroke: true,
	fillColor: options.colorFunction(properties.VALUE),
	color: options.colorFunction(properties.VALUE),
	weight: 1,
	fillOpacity: 1,
	opacity: 1

```
If I set `stroke: false` it does not draw borders of features but there is still an empty space between two adjustance cells which seems is for border. I ended up setting border's color same as fill. It works but it is a bit slower
