### ISSUE TITLE
How to replace a circle with a square, a pentagon or icons？

### ISSUE THREAD

**Issue by zeroHW** [Leaflet/Leaflet.VectorGrid#231]
There are many requirements in my project, such as filling lines and polygons with texture pictures and replacing circles with icons.How should this be done?Who guys has a good implementation can tell me?Thank you very much!

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).

**Comment by zeroHW** [comment]
@IvanSanchez Maybe I didn't make it clear. Leaflet.VectorGrid is being used in my project, but protobuf vector tiles cannot be filled with pictures or icons.Therefore, I raised this question.

**Comment by IvanSanchez** [comment]
> protobuf vector tiles cannot be filled with pictures or icons.

Yes they can.

**Comment by marcojulioarg** [comment]
> 
> 
> > protobuf vector tiles cannot be filled with pictures or icons.
> 
> Yes they can.

How?

**Comment by IvanSanchez** [comment]
> How?

https://github.com/Leaflet/Leaflet.VectorGrid/blob/master/docs/demo-points-icons.html

**Comment by marcojulioarg** [comment]
> 
> 
> > How?
> 
> https://github.com/Leaflet/Leaflet.VectorGrid/blob/master/docs/demo-points-icons.html

Thank you very much for the quick response. Does this work with the slicer too? I've tried to change the icon based on a property value with no avail.
