### ISSUE TITLE
Use with proj4leaflet

### ISSUE THREAD

**Issue by davidbrochart** [Leaflet/Leaflet.VectorGrid#233]
I was wondering if VectorGrid, in combination with [proj4leaflet](https://github.com/kartena/Proj4Leaflet), could allow to show a map in (virtually) any projection? Do the two plugins play well together?

Also posted in https://github.com/kartena/Proj4Leaflet/issues/173

**Comment by IvanSanchez** [comment]
VectorGrid was not designed with other projections in mind. Lack of widely-available vector tilesets in any other projections/tilegrids means that it never was a priority.

That said: if the tile naming scheme for your vector tiles fits the scheme of "normal" raster tiles, VectorGrid *should* work together with proj4leaflet. The easiest way to know for sure is if you publish your own vector tiles and try out.
