### ISSUE TITLE
Why is canvas tiles called Vector tiles?

### ISSUE THREAD

**Issue by nithinbandaru1** [Leaflet/Leaflet.VectorGrid#238]
Hi,
Maybe this is not the right place to ask this question. But hoping I could get the answer here because of the knowledge and experience you guys have and quite relevant to this library.

The question is simple why canvas tails are called Vector tiles. If we need to call them as Vector tiles then they should be made of SVG right? Canvas is still raster-based, right?

I was searching if there are any map tails providers in SVG format. I came across a few libraries saying they can provide vector-based tiles. But when I looked into the HTML. They are basically made using Canvas.

I was assuming that Vector tiles mean we would be receiving tails in form of SVG paths like borders etc, but it seems that not the case. I was also thinking that it would be really nice for doing some animations, drill-downs, styling, etc without much effort.

For example if I want to drill down on click or zoom like Countries -> States -> Regions -> Subregions etc. I have to maintain all the border information in SVG format of all levels and then handle click, zoom events, etc which is more like building as Base Map data service that provides Base Map.

With regards,
Nithin B.

**Comment by IvanSanchez** [comment]
https://en.wikipedia.org/wiki/Vector_tiles
