### ISSUE TITLE
MIT License

### ISSUE THREAD

**Issue by wilg** [Leaflet/Leaflet.VectorGrid#25]
The Beerware license is fun, but a more typical license like MIT or Apache would make using this project a bit easier to legally reason about integrating. Those licenses are basically "pre-approved" for use in many larger organizations.

**Comment by IvanSanchez** [comment]
I'm not willing to relicense my work at this point.

**Comment by wilg** [comment]
OK, I understand, thanks for considering it!

**Comment by wilg** [comment]
I hope I'm not being bothersome, but I thought I'd just give a quick rationale for why I think a different license would be appropriate:

First, the Beerware license has some [inherent issues](https://romanrm.net/beerware), including the fact that [it's not OSI approved and doesn't disclaim liability](https://github.com/github/choosealicense.com/issues/52#issuecomment-21128852).

Also, this library only contains the Beerware license text in README.md but particularly mentions that it only covers "this file" – meaning the other files in the repository are not clearly licensed. Additionally there are multiple contributors to the README so the claim of who wrote that file is technically incorrect in a sense.

These legal technicalities are pretty tedious, I'll admit, but IMHO it's good to be covered by a common, highly-audited license. If you're reluctant to switch licenses entirely, perhaps a dual license approach could work?

Anyway, hopefully this request isn't too irritating – I'll buy you a beer 🍺 regardless!
