### ISSUE TITLE
protobuf vectorgrid is not handling Long Integers why?

### ISSUE THREAD

**Issue by syamasundararao** [Leaflet/Leaflet.VectorGrid#250]
I have feature with id **1126128864018916581** but in protobuf vectorgrid it was showing as **1126128864018916000**.  Why? 
How i can use same value

**Comment by IvanSanchez** [comment]
> Why?

Because Javascript uses exclusively 64-bit floating-point format for numbers, and 1126128864018916581 doesn't fit in a 53-bit mantissa. Read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number and https://en.wikipedia.org/wiki/IEEE_754 .

**Comment by IvanSanchez** [comment]
Oh, duplicate of https://github.com/mapbox/pbf/issues/126 BTW.

**Comment by syamasundararao** [comment]
> > Why?
> 
> Because Javascript uses exclusively 64-bit floating-point format for numbers, and 1126128864018916581 doesn't fit in a 53-bit mantissa. Read https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number and https://en.wikipedia.org/wiki/IEEE_754 .
I understood the issue
But How can i use the same value . is there any possibility of adding support of long int

**Comment by IvanSanchez** [comment]
Ensure that your IDs are instances of [`BigInt`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt), or strings. I don't recall any VectorGrid code forcing IDs to be `Number`s.
