### ISSUE TITLE
Define bounds or extent of VectorGrid layer

### ISSUE THREAD

**Issue by bowguy** [Leaflet/Leaflet.VectorGrid#256]
I have a VectorGrid layer working fine in a Leaflet map.  The layer only covers one county in the US.  When I pan out of the county, it still continues to request tiles even though there is nothing there.  I have set up GeoServer to return the tiles outside the bounds, but the map is still making the request adding to bandwidth.  Is there a way to define the VectorGrid layer to only retrieve within the specified bounds or extent?

**Comment by IvanSanchez** [comment]
This is one of those RTFM things.

From https://leaflet.github.io/Leaflet.VectorGrid/vectorgrid-api-docs.html#vectorgrid :

> Extends Leaflet's L.GridLayer.

And then, https://leafletjs.com/reference-1.7.1.html#gridlayer-bounds

**Comment by bowguy** [comment]
Perfect.  Thanks for the M links - I'll take care of the RTF part
