### ISSUE TITLE
vectorTile doesn't have the correct styles

### ISSUE THREAD

**Issue by ellayunyun** [Leaflet/Leaflet.VectorGrid#27]
I am encounting the problem that inside createTile function, 
the line where it loops through the styleOptions `for (var j in styleOptions) {`,  sometimes even if the `styleOptions.length =1`, the j will loop to `"contains"` (more than 0). This results the layer not correctly styled after slicer. Do you have any clue, what might be the problem?

**Comment by IvanSanchez** [comment]
> Would you please instruct how to solve this problem?

The answer is "no". I'm not your teacher or instructor. When filing a bug report, it is *your* duty to show *me* that I have a mistake in *my* code so I can *fix* it. This is different from instructing or teaching.

**Comment by ellayunyun** [comment]
Yes, I do understood that it would be handy to have a working fiddle to "show" you where went wrong. But due to the project, it is difficult for me to show all the configurations etc. But bear me, I will try my best to explain my problem. I am using react in this project together with leaflet.vectorgrid

 var slicedtile = L.vectorGrid.slicer(geodata, {
      rendererFactory: L.canvas.tile,
      vectorTileLayerStyles: {
          sliced:{
            fillColor: 'red',
            fillOpacity: 0.5,
            stroke: false,
            color: 'transparent',
            fill: true,
            opacity: 0.2,
            weight: 0
            }       
       }                             
    }).addTo(this.state.map);       

However I couldn't remove/override the default settings of L.Path(which is configured under leaflet-src.js) by the function listed above. Then I looked into "Leaflet.VectorGrid.bundled.js" file under "leaflet.vectorgrid/dist/". Where I found out that at the line of 
 "for (var j in styleOptions) {
	**var style = L.extend({}, L.Path.prototype.options, styleOptions[j]);**" 
despite the length of styleOptions is only 1. "j" could still loop to "contains" (which I have no idea it comes from.) And "styleOptions[j]" would be a function which is shown as "
function(item){	 
       for (var i = 0, el = this[i]; i < this.length; el = this[++i]) {
	            if (item === el) return true;
	        }
	        return false;
	}
"
So my current solution is to change the above bold line into "var style = L.extend({}, L.Path.prototype.options, styleOptions[j]);", then it solves my problem. However I don't want to manually change the "Leaflet.VectorGrid.bundle.js", that's why I would like to ask whether you guys have any idea of this.

Thanks.

**Comment by IvanSanchez** [comment]
What's the full value of `styleOptions` when entering the loop?

> However I couldn't remove/override the default settings of L.Path

Why do you need/want to do that?

**Comment by ellayunyun** [comment]
the value of styleOptions is:
```
Object

color: "transparent"

fill: true

fillColor: "red"

fillOpacity: 0.5

opacity: 0.2

stroke: false

weight: 0

Object Prototype

__defineGetter__(propertyName, getterFunction)

__defineSetter__(propertyName, setterFunction)

__lookupGetter__(propertyName)

__lookupSetter__(propertyName)

constructor: function()

hasOwnProperty(propertyName)

isPrototypeOf(property)

propertyIsEnumerable(propertyName)

toLocaleString()

toString()

valueOf()
```
This is the value that I passed into leaflet.vectorgrid, when I called **vectorTileLayerStyles.**
The reason I would like to override the default setting of L.Path is because  "This resulted grids with strokes which are blue (this is the background I don't want.) " Since I am making something like a heatmap, so with the strokes as the borders of the polygons don't look nice. 

And I think if there can be an extra check on the object of styleOptions, as follows:
```
for (var j in styleOptions) {
                            if (!styleOptions.hasOwnProperty(j)){
                                   var style = L.extend({}, styleOptions[j]);
                            }else{                            

							var style = L.extend({}, L.Path.prototype.options, styleOptions[j]);
                            }
```
this can also solve my issue...

**Comment by ellayunyun** [comment]
Would you consider to have this extra check to whether this key (in this case is "j") is from the prototype chain or directly from the object itself.

Detail examples, you can see in this post: http://stackoverflow.com/questions/13632999/if-key-in-object-or-ifobject-hasownpropertykey from stackoverflow
.

**Comment by ellayunyun** [comment]
Also on https://developer.mozilla.org/nl/docs/Web/JavaScript/Inheritance_and_the_prototype_chain

" To check whether an object has a property defined on itself and not somewhere on its prototype chain, it is necessary to use the hasOwnProperty method which all objects inherit from Object.prototype.

hasOwnProperty is the only thing in JavaScript which deals with properties and does not traverse the prototype chain.

Note: It is not enough to check whether a property is undefined. The property might very well exist, but its value just happens to be set to undefined."

**Comment by ElessarWebb** [comment]
There actually does seem to be a bug in the mentioned code (line 142 in Leaflet.Vectorgrid.js). If you log the value of `j` inside the forloop there, it takes the value of functions like `contains`. In some cases this indeed causes wrong application of styles. 

I don't entirely understand what's happening and why and nor do I have a standalone example of the bug, but nonetheless, the above observation that `j` in `for(var j in someObject)` should be guarded not to loop over the prototype using `hasOwnProperty` always applies.

**Comment by jkuebart** [comment]
This problem is easy enough to reproduce by adding an enumerable property to Array.prototype, for example `Array.prototype.fuddle = true`.

All the `for`...`in` loops should be rewritten using `Object.keys` or have an additional `hasOwnProperty` check.

If you're adding properties to `Array.prototype` yourself, make sure to use `Object.defineProperty` to make them non-enumerable. This will this type of problem.
