### ISSUE TITLE
No Tile rendering with leaflet 1.0.2

### ISSUE THREAD

**Issue by manuamador** [Leaflet/Leaflet.VectorGrid#31]
Hi,
No error in the console logs.
But tiles are not rendering with Leaflet 1.0.2.
I will try to investigate a bit.
Very nice package BTW.

**Comment by IvanSanchez** [comment]
Can you publish a fiddle/codepen/[playground](https://playground-leaflet.rhcloud.com/) that displays this behaviour? That works with Leaflet 1.0.1 but fails with 1.0.2?

**Comment by manuamador** [comment]
https://playground-leaflet.rhcloud.com/xalil/edit?html,output

**Comment by perliedman** [comment]
Canvas rendering is currently broken with 1.0.2, but I'm working on a fix for this.

For a really quick workaround, you can probably just add this line to `L.Canvas.Tile`'s `initialize` method:

```js
		this._drawing = true;
```

**Comment by manuamador** [comment]
Thanks !
