### ISSUE TITLE
Styles set per feature are not set when new tiles are loaded

### ISSUE THREAD

**Issue by perliedman** [Leaflet/Leaflet.VectorGrid#33]
When the `setFeatureStyle` method is used, it only updates the currently loaded tiles. When a new tile, that might be part of the feature, is loaded, it will get the default styling. This can appear as tears between tiles, and also makes overridden styles disappear once the map is zoomed.

**Comment by lediur** [comment]
I've also noticed this - if I add a vector grid layer to the map, and then immediately try to set styles on it (as part of a React app), no styles get applied since the vector tiles haven't been loaded yet.
