### ISSUE TITLE
Not showing any map, throwing error

### ISSUE THREAD

**Issue by skylarmt** [Leaflet/Leaflet.VectorGrid#36]
I'm trying to use vector tiles in a Cordova Android app, but tiles aren't showing up, and I get the following error in the console:

`Uncaught (in promise) TypeError: reader.addEventListener is not a function (19:01:35:244 | error, javascript)
    at (anonymous function) (www/js/Leaflet.VectorGrid.bundled.js:1676:13)
    at (anonymous function) (www/js/Leaflet.VectorGrid.bundled.js:1675:12)`

I copy-pasted the code from the example into my app on top of the old raster tile layer code.

**Comment by IvanSanchez** [comment]
Hi, and thanks for taking the time to open a bug report in Leaflet.

However, in this repository we only handle bugs in "[vanilla](http://vanilla-js.com/)" Leaflet. This means that we do **not** handle bugs which are specific to frameworks such as:
* React
* Ractive
* AngularJS
* Leaflet for R
* Joomla
* Wordpress
* Ionic
* Cordova
* Vue
* Electron
* Polymer
* ...etc

Please understand that we only have the time and energy to test Leaflet in plain web browsers.

Please try to either reproduce the bug without using any frameworks, or submit a bug to the appropiate repo.
