### ISSUE TITLE
Performance vs Leaflet 0.7

### ISSUE THREAD

**Issue by reyemtm** [Leaflet/Leaflet.VectorGrid#39]
I am not sure why, but a very similar method of creating and rendering vector tiles using Leaflet 0.7 and canvas has notably better performance. I did not create this method so I can't speak to how it works, but I am using it in a few maps. Panning and zooming are much faster and smoother in 0.7. There is a lag when panning and zooming in Leaflet 1.0 that makes the map seems slow. Possibly there are settings to tweak to get better performance from this plugin and Leaflet 1.0?

Yes I have a ton of other plugins loaded in these maps, but it should give some general idea of performance losses with Leaflet 1.0 and this plugin. Both maps use the same data, the only difference is the leaflet version and the method for creating and drawing the vector tiles.

[Leaflet 0.7](http://www.ovrdc.org/apps/gallia-parcels-v1.html)

[Leaflet 1.0 & Leaflet Vector Grid](https://www.ovrdc.org/apps/gallia-parcels.html)

Any ideas on performance tweaks would be appreciated. I have increased the simplification factor and lowered the max point index in the Leaflet 1.0 example, but with little improvement.

**Comment by perliedman** [comment]
Your Leaflet 0.7 example uses the canvas renderer, while your Leaflet.VectorGrid setup uses the SVG renderer. The SVG renderer will not perform well on large datasets (although your example actually works pretty well on my machine).

Switch to using the Canvas renderer in Leaflet.VectorGrid and you should see much better performance; see the [SVG vs <canvas>](https://github.com/Leaflet/Leaflet.VectorGrid#svg-vs-canvas) section of the docs.

**Comment by perliedman** [comment]
My primary use for Leaflet.VectorGrid is actually displaying parcel data, and I've successfully used it with >200k parcels on mobile, although performance isn't great at that point.

**Comment by reyemtm** [comment]
Thanks!

Ok, that works much better, with a few caveats, the main one being the current bundled unpkg version does not seem to draw the canvas layer, though it is there. Not sure what the issue is. I am using the bundled version linked to in the demos. I will update my original comment with the new canvas link.

**Comment by perliedman** [comment]
@reyemtm ok, yes the last released version of VectorGrid unfortunately doesn't work with Leaflet 1.0.2. I did some heavy work on canvas in Leaflet because of the changes I made in VectorGrid, but I also had to break the internals to fix things.

Either try VectorGrid from `master`, or wait until we make a new release, which I hope will be soon.

**Comment by reyemtm** [comment]
Sounds good. Any chance you could send a link to the parcel viewer you
mentioned?

**Comment by perliedman** [comment]
@reyemtm unfortunately not open at the moment, don't know the exact timeline for when it will be released to the public, but I'll try to remember to post a link when it is!
