### ISSUE TITLE
Calling setFeatureStyle does not allow styling layers

### ISSUE THREAD

**Issue by lediur** [Leaflet/Leaflet.VectorGrid#41]
`setFeatureStyle` seems to take a bare `L.Path` style object, not a set of style objects as defined in the VectorGrid `vectorTileLayerStyles` options, which prevents styling named layers after the VectorGrid has been initialized. This issue is related to #40, since relying on the pre-existing layer names when calling `setFeatureStyle` doesn't work if the tiles haven't finished loading yet.

**Comment by perliedman** [comment]
Closed by merging #42.
