### ISSUE TITLE
Display the points-as-markers demo

### ISSUE THREAD

**Issue by IvanSanchez** [Leaflet/Leaflet.VectorGrid#45]
This repo is using `gh-pages` to host a built version of the files, plus all the demos.

The new demo added by @perliedman in #44 should be shown as well.

* [ ] Update `gh-pages` with the latest built files and demos (via a PR)
* [ ] Add link to the main `README.md`

**Comment by perliedman** [comment]
While modifying `README.md`, we might as well:

* [ ] add docs for `icon` styling option

**Comment by smartgeosystem** [comment]
Hello
For some reasons **demo-points-icons** doesn't work for me. 
The same time **demo-points** works with
`<script src="http://leaflet.github.io/Leaflet.VectorGrid/dist/Leaflet.VectorGrid.bundled.js"></script>`
and doesn't with
`<script src="https://unpkg.com/leaflet.vectorgrid@latest/dist/Leaflet.VectorGrid.bundled.js"></script>`
or
`<script src="/dist/Leaflet.VectorGrid.bundled.js"></script>`

**dist** files (Leaflet.VectorGrid.bundled.js, etc.) was created by npm install.
What might be the reason?

**Comment by perliedman** [comment]
@smartgeosystem Hi,

I'm interpreting the code you've pasted above as you're using latest VectorGrid from NPM to run the demo-points-icons? That will not work, since the icons functionality hasn't been released in any version yet, it's currently only in `master`.

Or did I misunderstand the problem you're seeing?

**Comment by smartgeosystem** [comment]
> That will not work, since the icons functionality hasn't been released in any version yet, it's currently only in master.

Oh, I see... Thanks!
