### ISSUE TITLE
Support setUrl like in TileLayer

### ISSUE THREAD

**Issue by frodrigo** [Leaflet/Leaflet.VectorGrid#49]
The VectorGrid layer may mimic the setUrl of TileLayer and the ability to update the URL once the layer is loaded.
http://leafletjs.com/reference-1.0.2.html#tilelayer-seturl

**Comment by IvanSanchez** [comment]
I expect this to be meant only for the `VectorGrid.Protobuf`. For `VectorGrid.Slicer` maybe a `setData` would also be useful.
