### ISSUE TITLE
Race between deleting vector tile layer and completing SVG tile additions from webworker

### ISSUE THREAD

**Issue by micahcatlin** [Leaflet/Leaflet.VectorGrid#56]
It's possible to add a layer which references vector tiles, then quickly remove the layer from a map.

When the webworker that process the PBF vector tiles finishes, it posts a message back to the main thread which results in an exception in Leaflet.Renderer.SVG.Tile.js

I think a safe solution is to have addTile just to silently drop a message which is trying to add a tile to a deleted layer.

eg.

https://github.com/Leaflet/Leaflet.VectorGrid/pull/57

**Comment by IvanSanchez** [comment]
This looks good. Can you please make a pull request out of that code change?

**Comment by micahcatlin** [comment]
Great.  I found a more general place to put the defensive code -- please consider PR #57
