### ISSUE TITLE
Points are cut at tile limit

### ISSUE THREAD

**Issue by vmeurisse** [Leaflet/Leaflet.VectorGrid#63]
Here is a picture of the issue
![image](https://cloud.githubusercontent.com/assets/1368138/22259710/a1cefe1e-e266-11e6-82a6-17b1241da06e.png)
and a live example
https://cdn.rawgit.com/vmeurisse/57314572b95621cf24f5407522855e08/raw/b33a7d58af1e0f70e3f14447a2bf174a66ef129b/vectorLayerPoint.html

**Comment by comick** [comment]
Have same issue. Point is clearly cut at tile border.
Rendered is rendering within tile bounds which makes sense in general and is the expected way to work.
Problem happens also using icon, with both svg and canvas rendered.

A possible solution: be able to style the layer in a way that dynamically adds/removes leaflet markers.

**Comment by perliedman** [comment]
For points to be rendered correctly when close to or at the tile boundary, they must also be present in the adjancent tiles' data.

As can be seen in the screenshot, the rendering is clipped at the tile border. If the point would also be present in adjacent tiles, each tile would render a clipped version of the point, but the union of these clipped renderings would be the complete symbol (circle).

To accomplish this, the tiles need to have some overlap, and the amount of overlap required actually depends on the size of the point symbolizer.

You can read more about the reasoning behind this in Mapbox's Vector Tile specification: https://www.mapbox.com/vector-tiles/specification/#clipping

**Comment by TroySchmidt** [comment]
For someone else finding this and looking for better direction, add ```buffer``` parameter to your options object you pass to ```L.vectorGrid.slicer```.  I set mine to 500 and now it is working as I would expect.
