### ISSUE TITLE
[WebWorker] Failed to Post Message

### ISSUE THREAD

**Issue by RishabhJain96** [Leaflet/Leaflet.VectorGrid#85]
I get the following error:

> Failed to execute 'postMessage' on 'Worker': An object could not be cloned.

Any ideas?

**Comment by IvanSanchez** [comment]
Unfortunately that's not enough information to know what's going on.

I suggest reading ["How To Ask Questions The Smart Way"](http://www.catb.org/esr/faqs/smart-questions.html) and ["How to Report Bugs Effectively"](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html) so you can make a better bug report.

**Comment by RishabhJain96** [comment]
The issue had to do with passing in extra objects into options. My guess is that https://github.com/Leaflet/Leaflet.VectorGrid/blob/master/src/Leaflet.VectorGrid.Slicer.js#L65 is not strict enough (classes can go through that cannot be passed).
