### ISSUE TITLE
Support for over zooming?

### ISSUE THREAD

**Issue by JamesMilnerUK** [Leaflet/Leaflet.VectorGrid#87]
Loving the project, working smoothly for me :) However one thing that would be interesting would be overzooming. Mapbox GL supports overzooming, causing max zoom levels to be extrapolated into further zoom levels. Is this something that would be useful? I could take a look at how this might be possible.

Heres a link to overzooming issue on Mapbox GL: https://github.com/mapbox/vector-tiles/issues/21

**Comment by perliedman** [comment]
Hi there, great to hear that you're finding VectorGrid useful!

It sounds like you want to use the `maxNativeZoom` and then set `maxZoom` to a higher value.

Note that there's an open issue on the implementation of `maxNativeZoom`, though: #74.

**Comment by pseudosig** [comment]
Are there any plans to support over zoom with vector tiles?

**Comment by perliedman** [comment]
@pseudosig not sure exactly what you mean, it _is_ supported now, but some changes/improvements are suggested in #74, those are the existing plans.

**Comment by jlezniak** [comment]
Interesting.  I'm currently using 1.2 and have tried the maxNativeZoom and maxZoom approach (is it supported a different way?), and it doesn't seem to work.  Probably doing something goofy.

**Comment by pseudosig** [comment]
Interesting. I'm currently using 1.2 and have tried the maxNativeZoom and maxZoom approach (is it supported a different way?), and it doesn't seem to work. Probably doing something goofy.

**Comment by perliedman** [comment]
@pseudosig sorry, my answer left out some important details. `maxNativeZoom` is supported in VectorGrid, but as mentioned in #69, it relies on a fix in _Leaflet_, which is currently only in the `master` branch, and not in a released version.

So, if you need this _now_, you probably want to use latest master of Leaflet as well as VectorGrid, or you will have to wait for a release.

**Comment by leye0** [comment]
@pseudosig  Is it now part of the release? Because it has no effect for me:
    var map = L.Map('map', {
      zoomAnimation: true,
      maxZoom: 22,
      maxNativeZoom: 16,
      minZoom: 8
    });
My tiles are rendered between 8 and 16. Leaflet.VectorGrid continues to zoom above maxNativeZoom until maxZoom, so I'm getting 404s.

**Comment by reyemtm** [comment]
I'm still not clear on overzoom - can I access vector tile features beyond the maxZoom?

**Comment by miroslawlis** [comment]
> I'm still not clear on overzoom - can I access vector tile features beyond the maxNativeZoom?
@reyemtm It works for me (kinda blury). Leaflet @1.7.1 and Leaflet.vectorGrid @ 1.3
`maxZoom: 20,
maxNativeZoom: 14,`
