### ISSUE TITLE
Need a polyfill for 'fetch'

### ISSUE THREAD

**Issue by aidangarza** [Leaflet/Leaflet.VectorGrid#96]
I'm building an app that uses multiple Protobuf tile layers. It is working great in Chrome, Firefox, and Edge, but was failing in Safari 10.0.3. Some digging revealed that the cause of the issue was the use of the native 'fetch' function in the `_getVectorTilePromise` method. The 'fetch' function is not supported in IE, or Safari 10 and earlier. There are polyfills available for this functionality that should be added to this project if the native 'fetch' function is going to be used e.g. https://github.com/github/fetch

**Comment by jdesboeufs** [comment]
Or just use https://polyfill.io/v2/docs/
Modern mobile phones don't have to pay this price ;)

**Comment by perliedman** [comment]
This was really closed by #98, but I agree with @jdesboeufs that a better solution is to leave it up to the application using Leaflet.VectorGrid to pull in any polyfills it needs. If every library includes polyfills (potentially different ones), there's going to be a lot of bloat.
